services:
  redis:
    image: redis:8.8.0-trixie
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    # volumes:
      # - redis_data_test:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  celery_worker:
    build:
      context: .
      target: test
    # image: python:3.12.13-slim-trixie
    # volumes:
      # - .:/app
    # working_dir: /app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    command: celery -A past_due_project worker --loglevel=info
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_beat:
    build:
      context: .
      target: test
    # image: python:3.12.13-slim-trixie
    # volumes:
      # - .:/app
    # working_dir: /app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    command: celery -A past_due_project beat --loglevel=info
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:4.3.1-management
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:18.4-trixie
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    # volumes:
      # - postgres_data_test:/var/lib/postgresql
    restart: unless-stopped
    
  web:
    build:
      context: .
      target: test
    # volumes:
      # - .:/past_due_app
    # ports:
      # - "127.0.0.1:8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=past_due_project.settings.test
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      # - DEBUG=1
      # - SECRET_KEY=dev_secret_key_django6
      # - DATABASE_URL=postgres://django_user:django_password@db:5432/django_db
    depends_on:
      - db
      - rabbitmq
      - redis
    # command: >
      # sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

# volumes:
  # postgres_data_test: