services:
  rabbitmq:
    image: rabbitmq:4.3.1-management
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:18.4-trixie
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql
    restart: unless-stopped
  
  web:
    build:
      context: .
      target: development
    volumes:
      - .:/past_due_app
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=past_due_project.settings.dev
      # - DEBUG=1
      # - SECRET_KEY=dev_secret_key_django6
      # - DATABASE_URL=postgres://django_user:django_password@db:5432/django_db
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data_dev: